/**
 * Manifeste — CATALOGUE (composants hors tranche pilote).
 * Entrées volontairement plus compactes : elles suffisent au routage des agents
 * (existence, import, axes, défauts, anti-patterns). Chaque composant rejoindra le
 * niveau de détail du pilote lors de sa vague de propagation (cf. plan de migration).
 * Les axes vérifiés par tsc (via `axe<U>()`) sont branchés là où le composant exporte
 * son union ; les autres le seront au moment de leur vague.
 */
import { axe, type Entree } from "./schema";
import type { VariantProps } from "class-variance-authority";

type AlertTone = NonNullable<VariantProps<typeof import("../components/alert/alert").alertRootVariants>["tone"]>;
type ToastTone = import("../components/toast/toast").ToastTone;
type DrawerSide = import("../components/drawer/drawer").DrawerSide;
type DrawerSize = import("../components/drawer/drawer").DrawerSize;
type DrawerEffect = import("../components/drawer/drawer").DrawerEffect;
type ModalPlacement = import("../components/modal/modal").ModalPlacement;

export const catalogue: Entree[] = [
  {
    name: "Accordion",
    package: "@fili/react",
    import: 'import { Accordion } from "@fili/react";',
    status: "stable",
    category: "contenu",
    purpose: "Sections dépliables (multi-ouvert par défaut) — headings réels + aria-expanded.",
    doctrine: { ux: "components/ACCORDION-UX.md", ui: "components/ACCORDION-UI.md" },
    rules: "RULES-accordion.md",
    anatomy: ["Accordion", "Accordion.Item", "Accordion.Header", "Accordion.Panel"],
    props: {
      type: { type: '"single" | "multiple"', default: '"multiple"', description: "single = un seul panneau ouvert." },
      level: { type: "2…6", default: "3", description: "Niveau de heading réel du Header." },
    },
  },
  {
    name: "Alert",
    package: "@fili/react",
    import: 'import { Alert } from "@fili/react";',
    status: "stable",
    category: "message",
    purpose: "Message contextuel persistant. L'icône est la silhouette normative du tone — jamais retirée.",
    doctrine: { ux: "components/ALERT-UX.md", ui: "components/ALERT-UI.md" },
    rules: "RULES-alert.md",
    anatomy: ["Alert.Root", "Alert.Icon", "Alert.Content", "Alert.Title", "Alert.Description", "Alert.Actions", "Alert.Close"],
    axes: {
      tone: axe<AlertTone>({
        kind: "tone",
        description: "Sémantique du message (registre messages du dictionnaire des tones).",
        values: { info: "information", success: "confirmation", warning: "avertissement", danger: "erreur/danger" },
        default: "info",
      }),
    },
    props: {
      live: { type: "boolean", default: "false", description: "true → role=alert (danger/warning) ou role=status." },
    },
    antiPatterns: ["S'en servir comme bouton warning (l'avertissement est un message, pas une action)"],
  },
  {
    name: "AppLayout",
    package: "@fili/react",
    import: 'import { AppLayout } from "@fili/react";',
    status: "stable",
    category: "gabarit",
    purpose: "Façade du shell applicatif (sidebar repliable, topbar, aside) pilotée par la largeur du shell, pas du viewport.",
    doctrine: null,
    rules: null,
    props: {
      variant: { type: '"default" | "docs"', default: '"default"', description: "Gabarit app ou documentation." },
      collapsible: { type: "boolean", default: "true", description: "Rail de navigation repliable." },
    },
  },
  {
    name: "AppShell",
    package: "@fili/react",
    import: 'import { AppShell } from "@fili/react";',
    status: "interne",
    category: "gabarit",
    purpose: "Primitive bas-niveau à 3 régions sous AppLayout. Préférer AppLayout ; statut interne recommandé (zéro consommateur).",
    doctrine: null,
    rules: null,
  },
  {
    name: "Brand",
    package: "@fili/react",
    import: 'import { Brand } from "@fili/react";',
    status: "stable",
    category: "identité",
    purpose: "Verrou logo + nom pour la tête de rail.",
    doctrine: null,
    rules: null,
    anatomy: ["Brand.Root", "Brand.Logo", "Brand.Text"],
  },
  {
    name: "CardGroup",
    package: "@fili/react",
    import: 'import { CardGroup } from "@fili/react";',
    status: "stable",
    category: "collection",
    purpose: "LA collection de cartes : grille intrinsèque, un seul mode pour toute la collection, proximité au survol.",
    doctrine: { pattern: "patterns/COLLECTION-UX.md + COLLECTION-UI.md" },
    rules: "RULES-collection.md",
    props: {
      cols: { type: '1 | 2 | 3 | 4 | "auto"', default: '"auto"', description: "auto = grille intrinsèque (jamais un nombre par appareil)." },
      density: { type: '"spacious" | "comfortable" | "compact"', default: '"comfortable"', description: "Densité de la collection." },
      mode: { type: '"static" | "clickable" | "selectable"', default: '"static"', description: "Mode UNIQUE pour toute la collection." },
      orientation: { type: '"stacked" | "inline"', default: '"stacked"', description: "Cartes empilées ou en ligne." },
    },
    antiPatterns: ["Grille de cartes à la main (grid-cols-* par breakpoint viewport) — la collection est intrinsèque"],
  },
  {
    name: "Container",
    package: "@fili/react",
    import: 'import { Container } from "@fili/react";',
    status: "stable",
    category: "gabarit",
    purpose: "Cadre de page (max-width + centrage). Le cran suit le contexte : narrow = formulaire, default = contenu, wide = dashboard.",
    doctrine: { pattern: "foundations/GRID" },
    rules: null,
    props: {
      size: { type: '"narrow" | "default" | "wide" | "full"', default: '"default"', description: "Largeurs de contenu (langue narrow/default/wide — jamais sm/md/lg)." },
    },
  },
  {
    name: "DeleteButton",
    package: "@fili/react",
    import: 'import { DeleteButton } from "@fili/react";',
    status: "expressif",
    category: "contrôle",
    purpose: "Bouton destructif E-motion (état terminal animé). Réservé aux moments mérités — budget de rareté.",
    doctrine: { ux: "components/BUTTON-UX.md §E-motion" },
    rules: null,
    props: {
      onDelete: { type: "() => Promise<unknown> | unknown", description: "Action de suppression." },
      size: { type: '"sm" | "md" | "lg"', default: '"lg"', description: "Taille du contrôle." },
    },
  },
  {
    name: "Divider",
    package: "@fili/react",
    import: 'import { Divider } from "@fili/react";',
    status: "stable",
    category: "structure",
    purpose: "Séparation décorative (ou sémantique avec decorative=false).",
    doctrine: { pattern: "foundations/BORDER" },
    rules: null,
    props: {
      orientation: { type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Sens du filet." },
      decorative: { type: "boolean", default: "true", description: "false → role=separator + aria-orientation." },
    },
  },
  {
    name: "Drawer",
    package: "@fili/react",
    import: 'import { Drawer } from "@fili/react";',
    status: "stable",
    category: "superposé",
    purpose: "Panneau ancré à un bord. Un « sheet » EST un Drawer top/bottom — pas de composant Sheet séparé.",
    doctrine: { pattern: "foundations/OVERLAY" },
    rules: null,
    anatomy: ["Drawer", "Drawer.Frame (requis pour push/depth)"],
    axes: {
      side: axe<DrawerSide>({
        kind: "enum",
        description: "Bord d'ancrage (directions logiques).",
        values: { start: "rail début", end: "rail fin", top: "feuille haute centrée", bottom: "feuille basse centrée" },
        default: "start",
      }),
      size: axe<DrawerSize>({
        kind: "enum",
        description:
          "Double lecture : largeur du panneau (start/end) ou de la feuille centrée (top/bottom). Défaut contextuel : narrow en start/end, full en top/bottom.",
        values: { narrow: "280 / 480px", default: "480 / 640px", wide: "640 / 1024px", full: "≈85% / pleine largeur" },
        default: null,
      }),
      effect: axe<DrawerEffect>({
        kind: "enum",
        description: "push impossible en vertical (repli overlay) ; push/depth exigent <Drawer.Frame>.",
        values: { overlay: "par-dessus + scrim", push: "pousse le contenu du Frame" },
        default: "overlay",
      }),
    },
    props: {
      open: { type: "boolean", required: true, description: "Contrôlé." },
      onClose: { type: "() => void", required: true, description: "Échap / scrim / bouton." },
      depth: { type: "boolean", default: "false", description: "Depth Transition (fond qui recule) — combinable." },
    },
  },
  {
    name: "Dropdown",
    package: "@fili/react",
    import: 'import { Dropdown } from "@fili/react";',
    status: "stable",
    category: "superposé",
    purpose: "Menu d'ACTIONS (jamais de valeur — ça, c'est Select). Placement auto par défaut ; Dropdown.Inline pour la forme à plat.",
    doctrine: { pattern: "foundations/OVERLAY" },
    rules: null,
    anatomy: ["Dropdown.Root", "Dropdown.Trigger", "Dropdown.Content", "Dropdown.Item", "Dropdown.Label", "Dropdown.Separator", "Dropdown.Inline"],
    props: {
      side: { type: '"top" | "bottom" | "auto"', default: '"auto"', description: "Placement mesuré à l'ouverture ; explicite = forçage." },
      align: { type: '"start" | "center" | "end" | "auto"', default: '"auto"', description: "Alignement." },
    },
    antiPatterns: ["Y mettre une sélection de valeur (→ Select)", "Item sans onSelect ni href"],
  },
  {
    name: "Link",
    package: "@fili/react",
    import: 'import { Link } from "@fili/react";',
    status: "stable",
    category: "contrôle",
    purpose: "La navigation. context règle la présentation (inline souligné, standalone, navigation avec current).",
    doctrine: { ux: "components/LINK-UX.md", ui: "components/LINK-UI.md" },
    rules: "RULES-link.md",
    props: {
      context: { type: '"inline" | "standalone" | "navigation"', default: '"standalone"', description: "Environnement d'usage." },
      current: { type: "boolean", description: "navigation seulement — aria-current + signal non chromatique." },
    },
    antiPatterns: ["Un <button> qui navigue, un Link qui mute (l'action, c'est Button)"],
  },
  {
    name: "Modal",
    package: "@fili/react",
    import: 'import { Modal } from "@fili/react";',
    status: "stable",
    category: "superposé",
    purpose: "Superposé modal centré (focus trap, scrim, Échap). Confirmation = narrow ; wide = illustration/tableau court.",
    doctrine: { ux: "components/MODAL-UX.md", ui: "components/MODAL-UI.md" },
    rules: "RULES-modal.md",
    anatomy: ["Modal.Root", "Modal.Header", "Modal.Body", "Modal.Footer", "Modal.Close"],
    axes: {
      placement: axe<ModalPlacement>({
        kind: "enum",
        description: "Position verticale de la surface.",
        values: { center: "centrée", top: "haut (retrait 6vh)", bottom: "bas" },
        default: "center",
      }),
    },
    props: {
      open: { type: "boolean", required: true, description: "Contrôlé." },
      onClose: { type: "() => void", required: true, description: "Fermeture." },
      size: { type: '"narrow" | "default" | "wide"', default: '"narrow"', description: "Largeurs de contenu." },
    },
  },
  {
    name: "Nav",
    package: "@fili/react",
    import: 'import { Nav } from "@fili/react";',
    status: "stable",
    category: "navigation",
    purpose:
      "Landmark de navigation (Root label requis) — porte LA facture unique de rangée de nav (navRowClass), consommée aussi par la nav intégrée d'AppLayout. Regroupement repliable = Accordion ; tête simple = Nav.GroupLabel.",
    doctrine: { pattern: "patterns/NAVIGATION" },
    rules: null,
    anatomy: ["Nav.Root", "Nav.List", "Nav.Link", "Nav.GroupLabel"],
    props: {
      current: { type: "boolean", description: "Page courante — aria-current=page + lavis primary-subtle + poids (un seul à la fois)." },
      asChild: { type: "boolean", default: "false", description: "Rend l'enfant à la place du <a> (next/link, bouton de sélection) — l'enfant compose icône + libellé tronqué." },
      icon: { type: "ReactNode", description: "Slot 16px avant le libellé (hors asChild)." },
    },
    antiPatterns: ["Recopier les classes de la rangée à la main (navRowClass est la seule définition)"],
  },
  {
    name: "Select",
    package: "@fili/react",
    import: 'import { Select } from "@fili/react";',
    status: "stable",
    category: "champ",
    purpose: "Choisir UNE valeur (combobox APG). native=true pour le menu de l'OS. Un menu d'actions, c'est Dropdown.",
    doctrine: { ux: "components/SELECT-UX.md", ui: "components/SELECT-UI.md" },
    rules: "RULES-select.md",
    props: {
      options: { type: "SelectOption[]", required: true, description: "Les choix." },
      value: { type: "string | null", required: true, description: "Contrôlé." },
      onValueChange: { type: "(v: string) => void", required: true, description: "Changement." },
      variant: { type: '"default" | "ghost"', default: '"default"', description: "Facture du déclencheur." },
      size: { type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille du contrôle." },
      native: { type: "boolean", default: "false", description: "<select> natif stylé." },
    },
  },
  {
    name: "Skeleton",
    package: "@fili/react",
    import: 'import { Skeleton } from "@fili/react";',
    status: "stable",
    category: "affichage",
    purpose: "Squelette de chargement. Autonome, ou via la prop `loading` des composants (préférer loading).",
    doctrine: null,
    rules: null,
    props: {
      variant: { type: '"block" | "text" | "circle"', default: '"block"', description: "Forme." },
      lines: { type: "number", description: "variant=text — dernière ligne raccourcie." },
    },
    antiPatterns: ["Recomposer un squelette à la main quand le composant expose loading"],
  },
  {
    name: "SkipLink",
    package: "@fili/react",
    import: 'import { SkipLink } from "@fili/react";',
    status: "stable",
    category: "navigation",
    purpose: "« Aller au contenu » (WCAG 2.4.1) — déplace réellement le focus.",
    doctrine: { pattern: "patterns/NAVIGATION" },
    rules: null,
  },
  {
    name: "SubmitButton",
    package: "@fili/react",
    import: 'import { SubmitButton } from "@fili/react";',
    status: "expressif",
    category: "contrôle",
    purpose: "Bouton d'envoi E-motion (avion en papier). Moments mérités seulement.",
    doctrine: { ux: "components/BUTTON-UX.md + patterns/FORM (S21)" },
    rules: null,
  },
  {
    name: "Switch",
    package: "@fili/react",
    import: 'import { Switch } from "@fili/react";',
    status: "stable",
    category: "champ",
    purpose: "Interrupteur à effet IMMÉDIAT (≠ checkbox). L'état se lit à la position du pouce, pas qu'à la couleur.",
    doctrine: { ux: "components/SWITCH-UX.md", ui: "components/SWITCH-UI.md" },
    rules: "RULES-switch.md",
    props: {
      checked: { type: "boolean", required: true, description: "Contrôlé." },
      onCheckedChange: { type: "(c: boolean) => void", description: "Bascule." },
      size: { type: '"sm" | "md" | "lg"', default: '"md"', description: "Taille." },
    },
    antiPatterns: ["S'en servir dans un formulaire soumis plus tard (→ checkbox à venir / statut requis)"],
  },
  {
    name: "Tabs",
    package: "@fili/react",
    import: 'import { Tabs } from "@fili/react";',
    status: "stable",
    category: "navigation",
    purpose: "Vues alternatives d'un même sujet (APG Tabs). Signal courant non chromatique.",
    doctrine: { ux: "components/TABS-UX.md", ui: "components/TABS-UI.md" },
    rules: "RULES-tabs.md",
    anatomy: ["Tabs.Root", "Tabs.List", "Tabs.Tab", "Tabs.Panel"],
    props: {
      variant: { type: '"line" | "pill"', default: '"line"', description: "Facture." },
      activation: { type: '"auto" | "manual"', default: '"auto"', description: "Activation au focus ou à l'entrée." },
    },
  },
  {
    name: "ThemeToggle",
    package: "@fili/react",
    import: 'import { ThemeToggle } from "@fili/react";',
    status: "stable",
    category: "contrôle",
    purpose: "Interrupteur clair/sombre (soleil ↔ lune).",
    doctrine: null,
    rules: null,
    props: {
      checked: { type: "boolean", required: true, description: "true = sombre." },
      onCheckedChange: { type: "(c: boolean) => void", required: true, description: "Bascule de thème." },
    },
  },
  {
    name: "Toast",
    package: "@fili/react",
    import: 'import { Toast, useToast } from "@fili/react";',
    status: "stable",
    category: "message",
    purpose: "Notification éphémère, API impérative : useToast().toast({...}) sous <Toast.Provider>. FIFO max 3, durée calculée.",
    doctrine: { ux: "components/TOAST-UX.md", ui: "components/TOAST-UI.md" },
    rules: "RULES-toast.md",
    axes: {
      tone: axe<ToastTone>({
        kind: "tone",
        description: "Sémantique du message — neutral (inverse haute-contraste) par défaut.",
        values: { info: "information", success: "confirmation", warning: "avertissement", danger: "erreur", neutral: "neutre inverse (défaut)" },
        default: "neutral",
      }),
    },
    props: {
      closing: { type: '"auto" | "close" | "timer"', default: '"auto"', description: "Mode de fermeture." },
      placement: { type: "ToastPlacement", default: '"bottom"', description: "Sur le Provider." },
    },
    antiPatterns: ["Toast pour une erreur bloquante (→ Alert dans le flux)"],
  },
  {
    name: "TableOfContents",
    package: "@fili/react",
    import: 'import { TableOfContents } from "@fili/react";',
    status: "stable",
    category: "navigation",
    purpose: "Sommaire scrollspy (aria-current=location).",
    doctrine: { pattern: "patterns/NAVIGATION" },
    rules: null,
  },
];
